package gaia.school.matricula.aluno;

public enum Curso {
    DESENVOLVIMENTO_WEB_FRONTEND,
    DESENVOLVIMENTO_WEB_BACKEND,
    DESENVOLVIMENTO_WEB_FULLSTACK,
    DATA_SCIENCE,
    DEVOPS,
    DESENVOLVIMENO_MOBILE,
    INFORMATICA_BASICA,
    CLOUD_ENGINNER,
}
